CREATE DATABASE Escola;
USE Escola;


CREATE TABLE PESSOA
(
	IDpessoa  INT IDENTITY(1,1) NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Idade INT NOT NULL,
	Endereco VARCHAR(150) NOT NULL,
	Contato VARCHAR (15),
	PRIMARY KEY (IDpessoa)
);


CREATE TABLE PROFESSOR
(
	IDprofessor INT IDENTITY(1,1) NOT NULL,
	IDpessoa INT NOT NULL,
	PRIMARY KEY (IDprofessor),
	FOREIGN KEY (IDpessoa) REFERENCES PESSOA (IDpessoa)
);


CREATE TABLE TURMA
( 
	IDturma INT IDENTITY(1,1) NOT NULL,
	Nome VARCHAR(55) NOT NULL,
	IDprofessor INT NOT NULL,
	PRIMARY KEY (IDturma),
	FOREIGN KEY (IDprofessor) REFERENCES PROFESSOR (IDprofessor)
);


CREATE TABLE RESPONSAVEL
(
	IDresponsavel INT IDENTITY(1,1) NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	IDpessoa INT NOT NULL,
	PRIMARY KEY (IDresponsavel),
	FOREIGN KEY (IDpessoa) REFERENCES PESSOA (IDpessoa)
);


CREATE TABLE ALUNO
(
	IDaluno INT IDENTITY(1,1) NOT NULL,
	Nome VARCHAR (100) NOT NULL,
	IDpessoa INT NOT NULL,
	IDresponsavel INT NOT NULL,
	IDturma INT NOT NULL,
	PRIMARY KEY (IDaluno),
	FOREIGN KEY (IDpessoa) REFERENCES PESSOA (IDpessoa),
	FOREIGN KEY (IDresponsavel) REFERENCES RESPONSAVEL (IDresponsavel),
	FOREIGN KEY (IDturma) REFERENCES TURMA (IDturma)
);
